### PR TITLE
feat: Improve protobuf version handling

### LINKED ISSUE #67: Improve Protoc version handling
## Issue Description

The current implementation assumes that Protobuf version always defines a major version, but there are cases where the major version may not always be present. As a result, the existing regular expression captures the minor number as the major and the patch number as the minor.

## Existing Modifications

There have been prior attempts to handle this issue, but they do not seem to provide a reliable solution.

## Context

**Embedded Proto Version:** 3.3.2

## Expected Behavior

When encountering Protobuf versions without a major version, the version handling should correctly identify and capture major, minor, and patch numbers.

## Observed Behavior

The script setup.py doesn't correctly identify and capture major, minor, and patch numbers.

## Steps to Reproduce

1. Encounter a Protobuf version without a major version (e.g., "libprotoc 25.0").
2. Try to use the setup.py script.

### PR DESCRIPTION
**Pull request by IronJulo**
fix #67

### CODE REVIEW

**Comment by BartHertog** [comment]
Hello IronJulo,

Thank you for sending in your pull request. I just merged in a different topic and broke the develop branch on the internal dev. sever. I will get back to you once it is fixed.

Best regards,

Bart

**Comment by IronJulo** [comment]
Hello,
Thanks you for your reply.

Best regards,
IronJulo

**Comment by BartHertog** [comment]
Had some problems not related to your work but with the CI checks. Fixed those and now your work will be merged into the develop branch.

Thank you for your help!

**Comment by IronJulo** [comment]
Thanks for resolving the issue and merging the contribution.

Best regards.

**Pull request merged**
