### PR TITLE
Use double braced initialization to support older compilers

### PR DESCRIPTION
**Pull request by surligas**
Signed-off-by: Manolis Surligas <surligas@gmail.com>

### CODE REVIEW

**Comment by BartHertog** [comment]
@surligas Thank you for making this pull request.

**Comment by surligas** [comment]
Hey @BartHertog, we faced this issue at the https://gitlab.com/librespacefoundation/satnogs/satnogs-tiny project using the latest platformio. I also checked that newer compilers are not have any issue with the double braced initialization.

**Comment by BartHertog** [comment]
@surligas Great to hear Embedded Proto is used in a space related application. 

With regards to your pull request. This is not the only location where arrays are initialized. In particular when using bytes, string or repeated message fields. Would it be required for these positions also? 

For our reference which compiler version is used in your application?

**Comment by BartHertog** [comment]
@surligas Your pull request has been merged via our dev server into release candidate branch rc-3.0.0. Thank you for your pull request.

**Pull request closed without merging**
